name: Build Padavan for NEWIFI3

on:
  workflow_dispatch: # Kích hoạt thủ công từ giao diện Actions Web

jobs:
  build:
    runs-on: ubuntu-22.04 # Nâng cấp lên Ubuntu 22.04 hiện đại và mượt mà hơn
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4 # Nâng cấp lên v4 mới nhất
      with:
        ref: dev # Chỉ định biên dịch đúng nhánh dev của bạn

    - name: Configure Fast APT Mirror
      run: |
        # Chuyển đổi máy chủ tải từ azure.archive sang mirrors.edge.kernel.org để đạt tốc độ tải cực nhanh, chống nghẽn mạng
        sudo sed -i 's/azure.archive.ubuntu.com/mirrors.edge.kernel.org/g' /etc/apt/sources.list

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin \
            libctf-nobfd0 libcunit1-dev libhdf5-dev libopenblas-dev -y

    - name: Prepare Toolchain and Copy Config Files
      run: |
        # 1. Chép đè file cấu hình bo mạch từ thư mục gốc vào đúng thư mục templates
        if [ -f "NEWIFI3.config" ]; then
          mkdir -p trunk/configs/templates
          cp -f NEWIFI3.config trunk/configs/templates/NEWIFI3.config
          
          # ĐỒNG THỜI CHÉP THẲNG THÀNH FILE .config ẨN TRONG THƯ MỤC TRUNK ĐỂ TRÁNH LỖI TRÌNH BUILD KHÔNG TÌM THẤY
          cp -f NEWIFI3.config trunk/.config
        fi
        
        # 2. Chép đè file cấu hình nhân từ thư mục gốc vào đúng thư mục boards
        if [ -f "kernel-3.4.x.config" ]; then
          mkdir -p trunk/configs/boards/NEWIFI3
          cp -f kernel-3.4.x.config trunk/configs/boards/NEWIFI3/kernel-3.4.x.config
        fi
        
        # Cấp quyền chạy cho các tệp thực thi chính
        chmod +x trunk/clear_tree
        chmod +x trunk/build_firmware_modify
        chmod +x toolchain-mipsel/dl_toolchain.sh

    - name: Download Prebuilt Toolchain
      run: |
        cd toolchain-mipsel
        sh dl_toolchain.sh

    - name: Compile Padavan Firmware
      run: |
        cd trunk
        sudo ./clear_tree
        fakeroot ./build_firmware_modify NEWIFI3

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@v4 # Nâng cấp lên v4 mới nhất để tối ưu tốc độ nén và tải lên tệp ROM
      with:
        name: Padavan_NEWIFI3_D2
        path: trunk/images/*.trx
