name: Build Padavan Firmware

on:
  workflow_dispatch: # Cho phép nhấn nút "Run workflow" thủ công trên web GitHub
  push:
    branches:
      - dev # Tự động build khi có push vào nhánh dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Bản vá/Cấu hình của bạn
      uses: actions/checkout@v4

    - name: Cài đặt các gói phụ thuộc (Dependencies)
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin \
            libctf-nobfd0 libcunit1-dev libhdf5-dev libopenblas-dev -y

    - name: Clone mã nguồn Padavan (yuos-bit)
      run: |
        # Clone vào thư mục /opt/rt-n56u giống như hướng dẫn của tác giả
        sudo git clone --depth=1 https://github.com/yuos-bit/Padavan.git /opt/rt-n56u
        sudo chown -R $USER:$GROUPS /opt/rt-n56u

    - name: Cấu hình File Custom (NEWIFI3 & Kernel)
      run: |
        # Copy file cấu hình máy từ thư mục gốc repo của bạn vào thư mục template của nguồn Padavan
        cp -f NEWIFI3.config /opt/rt-n56u/trunk/configs/templates/NEWIFI3.config
        
        # Nếu bạn có tùy chỉnh kernel, copy vào đúng vị trí cấu hình kernel tương ứng của chip (Newifi3 dùng mips)
        if [ -f "kernel-3.4.x.config" ]; then
          cp -f kernel-3.4.x.config /opt/rt-n56u/trunk/configs/boards/NEWIFI3/kernel-3.4.x.config
        fi

    - name: Chuẩn bị Toolchain (Mipsel)
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        # Sử dụng script download cho nhanh theo khuyến khích của tác giả
        sh dl_toolchain.sh

    - name: Compile Firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        # Chạy lệnh build với tham số truyền vào là NEWIFI3
        fakeroot ./build_firmware_modify NEWIFI3

    - name: Gom dữ liệu và Upload Firmware lên GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Padavan_NEWIFI3_Firmware
        path: /opt/rt-n56u/trunk/images/*.trx
        
